### ISSUE TITLE
Why PTQ doesn't use the Label of calibration data?

### ISSUE THREAD

**Issue by ugonfor** [hustvl/PD-Quant#1]
Thank you for open sourcing your great jobs. And I read your paper very interestingly. 

btw, I have a question. 
why PTQ doesn't use image label during calibration?

Many PTQ papers(including PD-quant) doesn't use the GT of calibration data, and they said, "PTQ should not use GT". So, I wonder why PTQ should not use the GT of calibration data. To confirm reason, I search many papers, but I failed to know reason.

![image](https://github.com/hustvl/PD-Quant/assets/56115311/eb0c4fd1-7bc4-4bc9-9d8f-3a762e905b58)
text in PD-quant

![image](https://github.com/hustvl/PD-Quant/assets/56115311/b187b080-4f3c-4ac9-9bb8-df9447012e25)
text in PD-quant

**Comment by jiawei-liu1103** [comment]
PTQ calibrates the quantized network using the intermediate  feature of the calibration data in the network, so labels are not necessary. Moreover, this quantization approach without labels is easier to deploy in practice.
